osx_image: xcode8
language: objective-c

before_install:
- travis_wait 35; bin/bootstrap-if-needed

script:
- xcodebuild clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
- xcodebuild clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-Mac -sdk macosx

notifications:
  email: false
