osx_image: xcode7.2
language: objective-c

before_install:
- brew update
- brew install carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- carthage update --platform iOS,Mac

script:
- xctool clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-iOS -sdk iphonesimulator
- xctool test -project OhMyAuth.xcodeproj -scheme OhMyAuth-iOS -sdk iphonesimulator
- xctool clean build -project OhMyAuth.xcodeproj -scheme OhMyAuth-Mac -sdk macosx
- xctool test -project OhMyAuth.xcodeproj -scheme OhMyAuth-Mac -sdk macosx
